model_dir: "model/"

retriever_config:
  module_name: "retriever"
  model_name: "zyw0605688/gte-large-zh:latest"
  base_url: "http://127.0.0.1:11434/v1"
  api_type: "openai"
  api_key: "null"

mllm_chat_bot_config:
  module_name: "chat_bot"
  model_name: "qwen2.5vl:7b"
  base_url: "http://127.0.0.1:11434/v1"
  api_type: "openai"
  api_key: "null"

chat_bot_config:
  module_name: "chat_bot"
  model_name: "qwen2.5:0.5b"
  base_url: "http://127.0.0.1:11434/v1"
  api_type: "openai"
  api_key: "null"
